import { fireEvent, render, screen, within } from '@testing-library/react'
import { MemoryRouter } from 'react-router'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { DriverPage } from './DriverPage'

beforeEach(() => {
  vi.useFakeTimers({ toFake: ['Date'] })
  vi.setSystemTime(new Date('2026-09-18T03:00:00.000Z'))
  window.confirm = vi.fn(() => true)
})

afterEach(() => vi.useRealTimers())

describe('ドライバー画面', () => {
  it('初期状態では架空ドライバーの選択を案内する', async () => {
    render(<MemoryRouter><DriverPage /></MemoryRouter>)
    expect(await screen.findByRole('heading', { name: 'ドライバー担当画面' })).toBeInTheDocument()
    expect(screen.getByText('担当ドライバーを選択してください')).toBeInTheDocument()
    expect(screen.getByText(/本番のログイン・本人確認を再現するものではありません/)).toBeInTheDocument()
  })

  it('担当案件から依頼時申告とドライバー向け指示を確認できる', async () => {
    render(<MemoryRouter><DriverPage /></MemoryRouter>)
    const driverSelect = await screen.findByLabelText('架空ドライバー')
    fireEvent.change(driverSelect, { target: { value: 'demo-driver-002' } })
    const list = screen.getByRole('region', { name: '架空 次郎の担当案件' })
    fireEvent.click(await within(list).findByRole('button', { name: /DEMO-012/ }))
    expect(screen.getByRole('heading', { name: '依頼時申告・目安' })).toBeInTheDocument()
    expect(screen.getByText('現場到着前に配車担当へ電話で確認')).toBeInTheDocument()
    expect(screen.queryByText(/現場で想定より量が多かったため/)).not.toBeInTheDocument()
  })

  it('選択したドライバーの予定だけを期間内で日付別に表示する', async () => {
    render(<MemoryRouter><DriverPage /></MemoryRouter>)
    const driverSelect = await screen.findByLabelText('架空ドライバー')
    fireEvent.change(driverSelect, { target: { value: 'demo-driver-001' } })
    fireEvent.click(screen.getByRole('button', { name: '期間を指定' }))
    fireEvent.change(screen.getByLabelText('開始日'), { target: { value: '2026-09-18' } })
    fireEvent.change(screen.getByLabelText('終了日'), { target: { value: '2026-09-27' } })
    const list = screen.getByRole('region', { name: '架空 太郎の担当案件' })
    expect(within(list).getByText(/DEMO-011/)).toBeInTheDocument()
    expect(within(list).queryByText(/DEMO-012/)).not.toBeInTheDocument()
    expect(screen.getByText(/今後の予定は、配車変更により更新される場合があります/)).toBeInTheDocument()
  })

  it('配車後の予約変更を変更項目の欄で強調表示する', async () => {
    render(<MemoryRouter><DriverPage /></MemoryRouter>)
    const driverSelect = await screen.findByLabelText('架空ドライバー')
    fireEvent.change(driverSelect, { target: { value: 'demo-driver-001' } })
    fireEvent.click(screen.getByRole('button', { name: '期間を指定' }))
    fireEvent.change(screen.getByLabelText('開始日'), { target: { value: '2026-09-28' } })
    fireEvent.change(screen.getByLabelText('終了日'), { target: { value: '2026-09-28' } })
    const list = screen.getByRole('region', { name: '架空 太郎の担当案件' })
    fireEvent.click(await within(list).findByRole('button', { name: /DEMO-016/ }))
    expect(within(list).getByText('要確認')).toBeInTheDocument()
    expect(within(list).getByText('要確認 1件')).toBeInTheDocument()
    expect(screen.getByText('予約・配車内容が変更されています')).toBeInTheDocument()
    expect(screen.getByText('赤い「要確認」が付いた項目を確認し、下の確認ボタンを押してください。')).toBeInTheDocument()
    expect(screen.queryByText(/配車担当者へ連絡/)).not.toBeInTheDocument()
    const answerSection = screen.getByRole('heading', { name: /依頼時申告・目安/ }).parentElement!
    expect(within(answerSection).getByText('要確認')).toBeInTheDocument()
    expect(answerSection).toHaveTextContent('変更前：棚 1台')
    expect(answerSection).toHaveTextContent('現在：棚 2台')
    const history = screen.getByRole('region', { name: '配車後の変更履歴' })
    const confirmButton = screen.getByRole('button', { name: '変更内容を確認しました' })
    expect(confirmButton.compareDocumentPosition(history) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    expect(history).toHaveTextContent('1件')
    expect(history).toHaveTextContent('棚 1台')
    expect(history).toHaveTextContent('棚 2台')
    expect(screen.getByRole('button', { name: '回収開始を記録' })).toBeDisabled()
    expect(screen.getByRole('button', { name: '作業結果を登録' })).toBeDisabled()
    fireEvent.click(confirmButton)
    await screen.findByText('変更内容を確認済みにしました。')
    expect(screen.queryByText('予約・配車内容が変更されています')).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '変更内容を確認しました' })).not.toBeInTheDocument()
    expect(screen.getByRole('region', { name: '配車後の変更履歴' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '回収開始を記録' })).toBeEnabled()
    expect(screen.getByRole('button', { name: '作業結果を登録' })).toBeEnabled()
  })

  it('任意の回収開始を記録し、一部回収として今回の配車を終了できる', async () => {
    render(<MemoryRouter><DriverPage /></MemoryRouter>)
    const driverSelect = await screen.findByLabelText('架空ドライバー')
    fireEvent.change(driverSelect, { target: { value: 'demo-driver-001' } })
    fireEvent.click(screen.getByRole('button', { name: '期間を指定' }))
    fireEvent.change(screen.getByLabelText('開始日'), { target: { value: '2026-09-26' } })
    fireEvent.change(screen.getByLabelText('終了日'), { target: { value: '2026-09-26' } })
    const list = screen.getByRole('region', { name: '架空 太郎の担当案件' })
    fireEvent.click(await within(list).findByRole('button', { name: /DEMO-011/ }))
    fireEvent.click(screen.getByRole('button', { name: '回収開始を記録' }))
    await screen.findByText('回収開始を記録しました。')
    expect(screen.getAllByText('回収中')).toHaveLength(2)
    fireEvent.click(screen.getByRole('button', { name: '作業結果を登録' }))
    const resultDialog = screen.getByRole('dialog', { name: '作業結果を登録' })
    fireEvent.click(within(resultDialog).getByRole('radio', { name: /一部回収/ }))
    fireEvent.click(within(resultDialog).getByRole('button', { name: '作業結果を保存して終了' }))
    expect(await within(resultDialog).findByText('実際の回収内容を入力してください。')).toBeInTheDocument()
    fireEvent.change(within(resultDialog).getByLabelText(/実際の回収内容/), { target: { value: '空き缶 1袋を回収' } })
    fireEvent.change(within(resultDialog).getByLabelText(/結果・次回対応メモ/), { target: { value: '残り1袋は別日に回収する' } })
    fireEvent.click(within(resultDialog).getByRole('button', { name: '作業結果を保存して終了' }))
    expect(await screen.findByText(/一部回収として作業を終了しました/)).toBeInTheDocument()
    expect(screen.getByText('この期間の担当案件はありません。')).toBeInTheDocument()
  })
})
