import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { MemoryRouter } from 'react-router'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { AdminPage } from './AdminPage'

beforeEach(() => {
  vi.useFakeTimers({ toFake: ['Date'] })
  vi.setSystemTime(new Date('2026-09-18T03:00:00.000Z'))
  sessionStorage.clear()
  window.confirm = vi.fn(() => true)
  window.prompt = vi.fn(() => '')
})

afterEach(() => vi.useRealTimers())

function renderPage() {
  return render(<MemoryRouter><AdminPage /></MemoryRouter>)
}

async function startAdmin() {
  fireEvent.click(screen.getByRole('button', { name: '管理画面を試す' }))
  await screen.findByText('受付件数')
}

describe('管理者画面', () => {
  it('初めて使う人へ配車前後の変更表示と数量の入力先を案内する', async () => {
    renderPage()
    await startAdmin()
    expect(screen.getByText(/連絡事項へ書いても数量欄は変わりません/)).toBeInTheDocument()
    expect(screen.getByText(/配車前の変更では表示されません/)).toBeInTheDocument()
  })

  it('初期表示月の予約を日付範囲内で一覧表示する', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    expect(screen.getByText('17件の予約')).toBeInTheDocument()
  })

  it('パスワードなしの案内から、集計と管理カレンダーを表示する', async () => {
    renderPage()
    expect(screen.queryByRole('textbox')).not.toBeInTheDocument()
    await startAdmin()
    expect(screen.getByText('デモ管理者モード')).toBeInTheDocument()
    expect(screen.getByText('確定件数')).toBeInTheDocument()
    const calendar = screen.getByRole('grid', { name: /管理カレンダー/ })
    expect(calendar).toBeInTheDocument()
    expect(within(calendar).getByText('受付停止 1')).toBeInTheDocument()
    expect(within(calendar).getByText('上限超過 1')).toBeInTheDocument()
    expect(within(calendar).getByText('配車要確認 1件')).toBeInTheDocument()
    expect(screen.getByLabelText('カレンダーの状態表示説明')).toHaveTextContent('数字は該当カテゴリー数')
    fireEvent.click(within(calendar).getByText('配車要確認 1件'))
    const dayDetail = screen.getByRole('complementary')
    expect(within(dayDetail).getByText(/DEMO-016/)).toBeInTheDocument()
    expect(within(dayDetail).getByText('要再確認')).toBeInTheDocument()
    fireEvent.click(within(calendar).getByText('受付停止 1'))
    let categoryStatus = screen.getByRole('region', { name: 'カテゴリー別受付状況' })
    let affectedCategory = within(categoryStatus).getByText('家具家財撤去').closest('article')!
    expect(within(affectedCategory).getByText('受付停止')).toBeInTheDocument()
    expect(within(affectedCategory).getByText('1 / 2件')).toBeInTheDocument()
    fireEvent.click(within(calendar).getByText('上限超過 1'))
    categoryStatus = screen.getByRole('region', { name: 'カテゴリー別受付状況' })
    affectedCategory = within(categoryStatus).getByText('蛍光管持込').closest('article')!
    expect(within(affectedCategory).getByText('上限超過')).toBeInTheDocument()
    expect(within(affectedCategory).getByText('3 / 2件')).toBeInTheDocument()
    const category = screen.getByLabelText('カテゴリー')
    expect(category).toHaveValue('')
    fireEvent.change(category, { target: { value: 'kagu' } })
    expect(within(screen.getByRole('grid', { name: /管理カレンダー/ })).getByText('受付停止')).toBeInTheDocument()
    fireEvent.change(category, { target: { value: '' } })
    const dayWithReceivedReservations = screen.getByRole('gridcell', { name: /^22\s*2件$/ })
    fireEvent.click(dayWithReceivedReservations)
    expect(within(screen.getByRole('complementary')).getAllByText('受付')).toHaveLength(2)
    expect(screen.getByRole('button', { name: '電話受付を登録' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '電話受付を登録' }))
    const editor = screen.getByRole('dialog', { name: '電話受付を登録' })
    expect(within(editor).getByLabelText('カテゴリー')).toHaveValue('keikoukan')
    expect(within(editor).getByLabelText('希望日')).not.toHaveValue('')
  })

  it('本日の未配車を至急警告し、対象日の未配車だけへ絞り込む', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: /本日の未配車が1件あります/ }))
    expect(screen.getByLabelText('予約状態')).toHaveValue('confirmed')
    expect(screen.getByLabelText('配車状況')).toHaveValue('unassigned')
    expect(screen.getByLabelText('開始日')).toHaveValue('2026-09-18')
    expect(screen.getByLabelText('終了日')).toHaveValue('2026-09-18')
    expect(await screen.findByText('DEMO-009')).toBeInTheDocument()
    expect(screen.queryByText('DEMO-014')).not.toBeInTheDocument()
  })

  it('予約一覧を検索し、予約詳細と操作履歴を表示する', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-003' } })
    fireEvent.click(await screen.findByText('DEMO-003'))
    expect(screen.getByRole('dialog', { name: 'DEMO-003' })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: '操作履歴' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '予約を確定する' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '配車を登録する' })).toBeDisabled()
    expect(screen.getByText('予約を確定すると配車を登録できます。')).toBeInTheDocument()
    fireEvent.keyDown(screen.getByRole('dialog', { name: 'DEMO-003' }), { key: 'Escape' })
    expect(screen.queryByRole('dialog', { name: 'DEMO-003' })).not.toBeInTheDocument()
  })

  it('予約状態と配車状況を別表示し、要再配車から対象予約を絞り込む', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: /^要再配車/ }))
    expect(screen.getByRole('columnheader', { name: '予約状態' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: '配車状況' })).toBeInTheDocument()
    expect(screen.getByLabelText('配車状況')).toHaveValue('needsRedispatch')
    expect(await screen.findByText('DEMO-014')).toBeInTheDocument()
  })

  it('操作履歴を予約作成から現在の状態まで古い順に表示する', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-002' } })
    fireEvent.click(await screen.findByText('DEMO-002'))
    const dialog = screen.getByRole('dialog', { name: 'DEMO-002' })
    const history = within(dialog).getByRole('heading', { name: '操作履歴' }).parentElement!
    expect(Array.from(history.querySelectorAll('strong'), (item) => item.textContent)).toEqual([
      '予約作成',
      '取消',
      '新しい予約として再受付（確定）',
    ])
    fireEvent.click(within(dialog).getByRole('button', { name: '予約詳細を閉じる' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-009' } })
    fireEvent.click(await screen.findByText('DEMO-009'))
    expect(within(screen.getByRole('dialog', { name: 'DEMO-009' })).getByText('取消予約から再受付（確定）')).toBeInTheDocument()
  })

  it('受付状態の予約を確定し、更新結果を表示する', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-003' } })
    fireEvent.click(await screen.findByText('DEMO-003'))
    fireEvent.click(screen.getByRole('button', { name: '予約を確定する' }))
    await waitFor(() => expect(screen.getByText('予約を「確定」に変更しました。')).toBeInTheDocument())
  })

  it('関連日追加では元予約のカテゴリーを引き継ぎ、日程確認を必須にする', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-003' } })
    fireEvent.click(await screen.findByText('DEMO-003'))
    fireEvent.click(screen.getByRole('button', { name: '関連する作業日を追加' }))
    const editor = screen.getByRole('dialog', { name: '関連する作業日を追加' })
    expect(within(editor).getByLabelText('カテゴリー')).toHaveValue('binkan')
    expect(within(editor).getByRole('checkbox', { name: '依頼者と追加日程を確認済み' })).not.toBeChecked()
  })

  it('取消予約の依頼者情報を使う場合は再受付画面であることを明示する', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-002' } })
    fireEvent.click(await screen.findByText('DEMO-002'))
    fireEvent.click(screen.getByRole('button', { name: 'この依頼者情報を使用する' }))
    const editor = screen.getByRole('dialog', { name: '取消予約から再受付' })
    expect(within(editor).getByText(/参照元：DEMO-002/)).toBeInTheDocument()
    expect(within(editor).getByLabelText('カテゴリー')).toHaveValue('kagu')
  })

  it('予約詳細内で配車の登録・変更・作業前取消を行える', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-010' } })
    fireEvent.click(await screen.findByText('DEMO-010'))
    let dialog = screen.getByRole('dialog', { name: 'DEMO-010' })
    fireEvent.click(within(dialog).getByRole('button', { name: '配車を登録する' }))
    fireEvent.change(within(dialog).getByLabelText(/^車両/), { target: { value: 'demo-vehicle-002' } })
    fireEvent.change(within(dialog).getByLabelText('主担当ドライバー'), { target: { value: 'demo-driver-003' } })
    fireEvent.change(within(dialog).getByLabelText(/ドライバー向け指示/), { target: { value: '到着前に担当者へ連絡' } })
    fireEvent.click(within(dialog).getByRole('button', { name: '配車を登録' }))
    await waitFor(() => expect(screen.getByText('配車を登録しました。')).toBeInTheDocument())
    dialog = screen.getByRole('dialog', { name: 'DEMO-010' })
    expect(within(dialog).getByText('第1便・配車済み')).toBeInTheDocument()
    fireEvent.click(within(dialog).getByRole('button', { name: '配車を変更する' }))
    fireEvent.change(within(dialog).getByLabelText('終了予定時刻'), { target: { value: '10:30' } })
    fireEvent.change(within(dialog).getByLabelText('主担当ドライバー'), { target: { value: 'demo-driver-002' } })
    fireEvent.click(within(dialog).getByRole('button', { name: '変更を保存' }))
    await waitFor(() => expect(screen.getByText('配車内容を変更しました。')).toBeInTheDocument())
    dialog = screen.getByRole('dialog', { name: 'DEMO-010' })
    expect(within(dialog).getByText(/担当変更：架空 三郎 → 架空 次郎（旧担当者未確認）/)).toBeInTheDocument()
    fireEvent.click(within(dialog).getByRole('button', { name: '配車を取り消す' }))
    await waitFor(() => expect(screen.getByText('配車を取り消しました。')).toBeInTheDocument())
    expect(within(screen.getByRole('dialog', { name: 'DEMO-010' })).getByText('第1便・配車取消')).toBeInTheDocument()
  })

  it('配車の必須項目が未選択なら理由を表示して登録を無効にする', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-010' } })
    fireEvent.click(await screen.findByText('DEMO-010'))
    const dialog = screen.getByRole('dialog', { name: 'DEMO-010' })
    fireEvent.click(within(dialog).getByRole('button', { name: '配車を登録する' }))
    const vehicle = within(dialog).getByLabelText(/^車両/)
    const driver = within(dialog).getByLabelText('主担当ドライバー')
    expect(vehicle).toHaveAttribute('aria-invalid', 'true')
    expect(driver).toHaveAttribute('aria-invalid', 'true')
    expect(within(vehicle.closest('.dispatch-editor-field')!).getByText('車両を選択してください。')).toBeInTheDocument()
    expect(within(driver.closest('.dispatch-editor-field')!).getByText('担当者を選択してください。')).toBeInTheDocument()
    expect(within(dialog).getByText('配車を登録できません')).toBeInTheDocument()
    expect(within(dialog).getByRole('button', { name: '配車を登録' })).toBeDisabled()
  })

  it('配車後の予約変更差分を確認済みにできる', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-016' } })
    fireEvent.click(await screen.findByText('DEMO-016'))
    const dialog = screen.getByRole('dialog', { name: 'DEMO-016' })
    expect(within(dialog).getByText(/依頼時申告：棚 1台 → 棚 2台/)).toBeInTheDocument()
    expect(within(dialog).getByText('変更内容が現在の配車に影響しないか確認してください。必要な場合は先に配車を変更します。')).toBeInTheDocument()
    expect(within(dialog).getByRole('button', { name: '回収開始を記録' })).toBeEnabled()
    expect(within(dialog).getByRole('button', { name: '作業結果を登録' })).toBeEnabled()
    fireEvent.click(within(dialog).getByRole('button', { name: '変更内容を確認済みにする' }))
    await waitFor(() => expect(screen.getByText('予約内容の変更を確認済みにしました。')).toBeInTheDocument())
    const updatedDialog = screen.getByRole('dialog', { name: 'DEMO-016' })
    expect(within(updatedDialog).queryByText('予約内容が配車後に変更されています')).not.toBeInTheDocument()
    expect(within(updatedDialog).getByText('ドライバー未確認')).toBeInTheDocument()
  })

  it('社内補足を追記し、予約詳細だけに表示する', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-005' } })
    fireEvent.click(await screen.findByText('DEMO-005'))
    const dialog = screen.getByRole('dialog', { name: 'DEMO-005' })
    fireEvent.change(within(dialog).getByLabelText(/社内補足を追加/), { target: { value: '午前中の訪問を電話で確認済み。' } })
    fireEvent.click(within(dialog).getByRole('button', { name: '社内補足を追加' }))
    await waitFor(() => expect(screen.getByText('社内補足を追加しました。')).toBeInTheDocument())
    expect(within(screen.getByRole('dialog', { name: 'DEMO-005' })).getByText('午前中の訪問を電話で確認済み。')).toBeInTheDocument()
  })

  it('配車重複時は保存せず、重複する受付番号と時間を表示する', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-014' } })
    fireEvent.click(await screen.findByText('DEMO-014'))
    const dialog = screen.getByRole('dialog', { name: 'DEMO-014' })
    fireEvent.click(within(dialog).getByRole('button', { name: '配車を登録する' }))
    fireEvent.change(within(dialog).getByLabelText('予定日'), { target: { value: '2026-09-28' } })
    fireEvent.change(within(dialog).getByLabelText(/^車両/), { target: { value: 'demo-vehicle-001' } })
    fireEvent.change(within(dialog).getByLabelText('主担当ドライバー'), { target: { value: 'demo-driver-001' } })
    expect(within(dialog).getAllByText(/この車両は同じ時間帯に2026年9月28日 09:00–10:00・DEMO-016で使用されています/).length).toBeGreaterThan(0)
    expect(within(dialog).getByRole('option', { name: /使用中：DEMO-016 09:00–10:00/ })).toBeDisabled()
    expect(within(dialog).getByRole('button', { name: '配車を登録' })).toBeDisabled()
  })

  it('既存予約のカテゴリーは変更できず、取消後の再受付を案内する', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-005' } })
    fireEvent.click(await screen.findByText('DEMO-005'))
    fireEvent.click(within(screen.getByRole('dialog', { name: 'DEMO-005' })).getByRole('button', { name: '変更' }))
    const editor = screen.getByRole('dialog', { name: '予約内容を変更' })
    expect(within(editor).getByLabelText(/カテゴリー/)).toBeDisabled()
    expect(within(editor).getByText(/予約を取り消し、正しいカテゴリーで再受付/)).toBeInTheDocument()
  })

  it('管理者が全量回収と搬入判断待ちを同時登録できる', async () => {
    renderPage()
    await startAdmin()
    fireEvent.click(screen.getByRole('button', { name: '予約一覧' }))
    fireEvent.change(screen.getByPlaceholderText('受付番号・会社名・担当者名・電話番号'), { target: { value: 'DEMO-012' } })
    fireEvent.click(await screen.findByText('DEMO-012'))
    const detail = screen.getByRole('dialog', { name: 'DEMO-012' })
    fireEvent.click(within(detail).getByRole('button', { name: '作業結果を登録' }))
    const resultDialog = screen.getByRole('dialog', { name: '作業結果を登録' })
    fireEvent.click(within(resultDialog).getByRole('radio', { name: /全量回収/ }))
    fireEvent.click(within(resultDialog).getByRole('checkbox', { name: /搬入判断待ち/ }))
    fireEvent.change(within(resultDialog).getByLabelText(/搬入できない理由/), { target: { value: '大雨のため搬入先へ進入できない' } })
    fireEvent.change(within(resultDialog).getByLabelText(/電話相談の状況/), { target: { value: '配車担当者へ報告し、受入再開を確認中' } })
    fireEvent.click(within(resultDialog).getByRole('button', { name: '作業結果を保存して終了' }))
    expect(await screen.findByText(/全量回収として作業を終了し、予約を完了しました。 車両を搬入判断待ちにしました/)).toBeInTheDocument()
    const updatedDetail = screen.getByRole('dialog', { name: 'DEMO-012' })
    expect(within(updatedDetail).getByText('第1便・全量回収済み')).toBeInTheDocument()

    fireEvent.click(within(updatedDetail).getByRole('button', { name: '積み置き中にする' }))
    fireEvent.change(within(updatedDetail).getByLabelText('電話相談の状況'), { target: { value: '翌営業日に搬入するまで車上保管する' } })
    fireEvent.click(within(updatedDetail).getByRole('button', { name: '保存する' }))
    expect(await screen.findByText('車両を積み置き中に変更しました。')).toBeInTheDocument()

    fireEvent.click(within(updatedDetail).getByRole('button', { name: '保留を解除する' }))
    fireEvent.change(within(updatedDetail).getByLabelText('積載解消の理由'), { target: { value: '搬入先で荷下ろしが完了した' } })
    fireEvent.click(within(updatedDetail).getByRole('button', { name: '保存する' }))
    expect(await screen.findByText('車両保留を解除しました。')).toBeInTheDocument()
  })
})
